module.exports = {
  NOTIFICATION_STATUS: {
    INIT: 'INIT',
    VIEWED: 'VIEWED', 
    READ: 'READ',
  },
  NOTIFICATION_TYPE: {
    THUMB_POST: 'THUMB_POST',
    THUMB_ARTICLE: 'THUMB_ARTICLE',
    THUMB_COMMENT: 'TTHUMB_COMMENT',
    THUMB_POST_COMMENT: 'THUMB_POST_COMMENT',

    COLLECT_POST: 'COLLECT_POST',
    COLLECT_ARTICLE: 'COLLECT_ARTICLE',

    SHARE_POST: 'SHARE_POST',
    SHARE_ARTICLE: 'SHARE_ARTICLE',

    COMMENT_POST: 'COMMENT_POST',
    COMMENT_POST_COMMENT: 'COMMENT_POST_COMMENT',
    COMMENT_ARTICLE: 'COMMENT_ARTICLE',
    COMMENT_COMMENT: 'COMMENT_COMMENT',
  }
};