module.exports = {
  TYPE: {
    NO_MYOPIA: 'NO_MYOPIA', // 无近视
    LOW_MYOPIA: 'LOW_MYOPIA', // 轻度近视
    MEDIUM_MYOPIA: 'MEDIUM_MYOPIA', // 中度近视
    HIGH_MYOPIA: 'HIGH_MYOPIA', // 高度近视

    NO_HYPEROPIA: 'NO_HYPEROPIA', // 无远视
    LOW_HYPEROPIA: 'LOW_HYPEROPIA', // 轻度远视
    MEDIUM_HYPEROPIA: 'MEDIUM_HYPEROPIA', // 中度远视
    HIGH_HYPEROPIA: 'HIGH_HYPEROPIA', // 高度远视

    NO_CYLINDRICAL: 'NO_CYLINDRICAL', // 无散光
    PHYSIOLOGICAL_CYLINDRICAL: 'PHYSIOLOGICAL_CYLINDRICAL', //生理性散光
    LOW_CYLINDRICAL: 'LOW_CYLINDRICAL', // 轻度散光
    MEDIUM_CYLINDRICAL: 'MEDIUM_CYLINDRICAL', // 中度散光
    HIGH_CYLINDRICAL: 'HIGH_CYLINDRICAL', // 高度散光
    /*
    轴长和角膜曲率
    */
    IN_RANGE: 'IN_RANGE',
    LESS_THAN_MIN: 'LESS_THAN_MIN',
    GREATER_THAN_MAX: 'GREATER_THAN_MAX'
  }
};